server:
  port: 8080

logging:
  level:
    ROOT: INFO
    az.mm.delivery: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-identity
          uri: http://localhost:8081/
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1
        - id: ms-order
          uri: http://localhost:8082/
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: ms-delivery
          uri: http://localhost:8083/
          predicates:
            - Path=/delivery/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  cors:
    allowedOrigins: "*"
    allowedHeaders: "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS