server:
  port: 8080

logging:
  level:
    ROOT: INFO
    az.mm.delivery: DEBUG

spring:
  application:
    name: api-gateway

zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignoredServices: '*'
  routes:
    ms-identity:
      path: /identity/**
      url: http://localhost:8081
    ms-order:
      path: /order/**
      url: http://localhost:8082
    ms-delivery:
      path: /delivery/**
      url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  cors:
    allowedOrigins: "*"
    allowedHeaders: "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
  filter:
    logging:
      skipped-urls: /actuator/health, /v2/api-docs/**, /v3/api-docs/**, /swagger-resources/**, /webjars/**, /favicon.ico



